export enum Projects {
    GET_PROJECTS_REQ = 'GET_PROJECTS_REQ',
    GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL',
    GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS',
    ADD_PROJECTS= 'ADD_PROJECTS',
    DELETE_PROJECTS = 'DELETE_PROJECTS',
    EDIT_PROJECTS = 'EDIT_PROJECTS',
}