export enum ToDos {
    GET_TODOS_REQ = 'GET_TODOS_REQ',
    GET_TODOS_FAIL = 'GET_TODOS_FAIL',
    GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS',
    ADD_TODOS = 'ADD_TODOS',
    DELETE_TODO = 'DELETE_TODO',
    EDIT_TODO = 'EDIT_TODO',
}